# Introdução

A esquizofrenia é um transtorno mental complexo e multifacetado que afeta milhões de pessoas em todo o mundo, aingindo cerca de aproximadamente 0.5% a 1% da população [@Simeone2015], classificada entre as 15 principais causas de incapacidade em todo o mundo em 2016 [@Burden2016].

É um dos diagnósticos mais clássicos da psiquiatria, mas ao mesmo tempo, um dos mais polêmicos e mais estigmatizantes [@Mannarini2022], havendo propostas para que tanto o nome "esquizofrenia" seja modificado [@Guloksuz2019; @Lasalvia2015; @Gaebel2019; @Maruta2019; @Chiu2022]. Em muitas situações os médicos evitam dar o diagnóstico aos pacientes, devido ao tamanho do estigma associado [@Sato2006]. Assim como os outros diagnósticos na psiquiatria, também não existem sintomas patognomônicos e não existem ainda marcadores biológicos, sendo até mesmo possível que esse diagnóstico represente na verdade um grupo heterogêneo de doenças mentais com sintomas similares. Além disso, os tratamentos atualmente disponíveis conseguem resolver apenas algumas dimensões dos sintomas (sintomas positivos), sendo ainda pouco efetivos para aliviarem os sintomas negativos e cognitivos associados à esquizofrenia [@Marder2023]. Além disso, o diagnóstico da esquizofrenia muitas vezes só é feito depois de muitos anos do início dos primeiros sintomas, havendo um lapso de anos de desenvolvimentos dos sintomas sem tratamento adequado, o que piora o prognóstico dos pacientes [@Hafner1998].

Ao longo dos anos, muitos psiquiatras e pesquisadores se dedicaram a estudar a evolução dos sintomas da esquizofrenia, buscando entender melhor como esse transtorno se desenvolve em suas fases iniciais, em suas fases ativas e em suas fases tardias. Compreender essa evolução é importante para que no futuro possamos ser capazes de diferenciar melhor os diferentes cluster desse transtorno na esperança que isso ajude tanto na escolha do tratamento mais adequado como na compreensão futura dos aspectos fisiopatologicos subjacentes.

Iremos abordar o início da construção do diagnóstico da Esquizofrenia, tal como proposto com Emil Kraepelin e Eugen Bleuler; os Sintomas de Primeira Ordem propostos por Kurt Schneider; os estágios iniciais da esquizofrenia, explorados de forma original por Klaus Conrad [@Conrad2] e Gerd Huber [@Huber]. Em seguida iremos abordar os estudos mais recentes sobre os desfechos da esquizofrenia.

O psiquiatra Emil Kraepelin elaborou, de forma original, a primeira concepção do que hoje denominamos esquizofrenia. Kraeplin denominou esse quadro de "Demencia Precoce" em contraposição à demência na fase tardia da vida descrita por seu colega Alois Alzheimer (REFERÊNCIA). Suas descrições evoluiram ao longo de anos, modificando-se aos poucos em cada uma das edições de seu tratado de psiquiatria e suas idéias estão presentes até hoje nos critérios diagnósticos atuais.

Eugen Bleuler, por dua vez, introduziu o termo "esquizofrenia" e postulou a existência de sintomas fundamentais e acessórios, ampliando o conceito do diagnóstico para além dos quadros graves descritos por Kraepelin.

Kurt Schneider, tentou elencar quais seriam os sintomas mais importantes para se pensar num diagnóstico de esquizofrenia, tendo elencado uma lista de sintomas que denominou de "Sintomas de Primeira Ordem" e "Sintomas de Segunda Ordem", até hoje discutidos na literatura médica.

Klaus Conrad, em sua obra seminal "A Esquizofrenia Incipiente" [^1.intro-1] [@Conrad, @Conrad2], explorou de maneira detalhada as fases iniciais da esquizofrenia, na qual os pacientes começam a experimentar uma desestruturação gradual da percepção da realidade. Conrad centrou-se nas experiências do paciente durante as fases prodrômica e psicótica precoce da esquizofrenia [@Mishara] e identificou uma sequência de mudanças psicológicas que antecedem o surgimento do delírio, introduzindo conceitos inovadores como *Trema* e *Apofania*.

[^1.intro-1]: Em espanhol: "La Esquizofrenia Incipiente. Intento de Un Analisis de la forma del delírio"

Gerd Huber introduziu o conceito de **Sintomas Básicos** (*Basic Symptoms*) da esquizofrenia, que são manifestações sutis e subjetivas reportadas pelos próprios pacientes. Esses sintomas incluem dificuldades de concentração, perturbações da percepção e pensamentos incoerentes. Huber argumentou que esses sintomas básicos são fundamentais para o diagnóstico precoce da esquizofrenia, pois podem preceder os sintomas mais floridos e típicos da fase aguda da doença.

A interseção entre os estágios iniciais da esquizofrenia descritos por Conrad e os sintomas básicos propostos por Huber oferece uma perspectiva enriquecedora sobre a identificação precoce e o manejo da esquizofrenia. Enquanto Huber destaca a importância das experiências internas dos pacientes, Conrad foca na progressão psicológica observável. Juntas, essas abordagens proporcionam uma compreensão mais abrangente e detalhada dos primeiros sinais da esquizofrenia. Esses estudos sugerem que a identificação precoce dos sintomas prodrômicos da esquizofrenia pode ser fundamental para o diagnóstico e tratamento eficaz desse transtorno. Reconhecer os sinais precoces da esquizofrenia pode permitir intervenções mais precoces e eficazes, ajudando a prevenir a progressão da doença e melhorar o prognóstico dos pacientes.

Finalmente, diversos estudos mais recentes tem mostrado a heterogeneidade dos desfechos da esquizofrenia, mostrando a necessidade de se pensar em diferentes subtipos de esquizofrenia, com diferentes prognósticos e diferentes respostas aos tratamentos. Esses estudos sugerem que a esquizofrenia pode ser uma síndrome clínica heterogênea, com diferentes subtipos clínicos e biológicos, o que pode ter implicações importantes para o diagnóstico e tratamento dessa doença \[REFERENCIA\].
